apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod
spec:
  namespaceSelector:
    matchNames:
    - kuadrant-system
  selector:
    matchLabels:
      app: istiod
  endpoints:
  - port: http-monitoring
